//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercuryshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Product_Size { get; set; }
        public Nullable<double> Product_Price { get; set; }
        public string Product_Img { get; set; }
        public Nullable<bool> Product_Status { get; set; }
        public Nullable<int> Product_Filter { get; set; }
        public Nullable<double> Product_Promotional_Price { get; set; }
        public string Product_Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual DatailProduct DatailProduct { get; set; }
    }
}
